### ISSUE TITLE
test functions in repo_processor.py

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/simple_grid_yaml_compiler#27]

**Comment by snehasi** [comment]
Hi @maany,

I went through the `simple_grid_yaml_compiler.py` script and followed all the references to `compiler.repo_processor`. Having went through all the functions in `compiler/repo_processor.py`, I think I  understand what each function is doing and would like to write tests for the same. Could help me with some pointers as to what all cases are we trying to cover with tests?

As a side note, I noticed that functions of type `get_*` have exactly same body except for the file name. Seeing the redundancy, maybe we can extract out this into a generalized function that will be called by all the `get_*` functions. I think this will eventually help reduce surface area for testing.

**Comment by maany** [comment]
@snehasi thanks for the PR, it's been merged. You make a good point regarding the get_* functions. I have created #36 to incorporate your suggestion. 
Feel free to take it up (if there's time left after you have finished your proposal)
Good luck 👍
