### ISSUE TITLE
global vars, default values are positioned in a wrong sequence

### ISSUE THREAD

**Issue by ejr004** [WLCG-Lightweight-Sites/simple_grid_yaml_compiler#45]
The compiler is positioning the config file before the default values from the component repositories. 

Error:
None, None, 'found undefined alias %r' % utf8(alias), event.start_mark
ruamel.yaml.composer.ComposerError: found undefined alias 'cream_default_var_ce_cpu_model'
  in "./.temp/runtime.yaml", line 59, column 23

**To Reproduce**
Just run the compiler giving a regular input file. And you will get the error

**Expected behavior**
Should put this config above and gives the augmented file

**Comment by maany** [comment]
#46
